### ISSUE TITLE
Various bugs

### ISSUE THREAD

**Issue by flogat** [shell-fire/shellfire-vpn#13]
- [x] Error message at wrong PW says "Null response received", better would be "Wrong Username/PW" or something like that
- [ ] When pressing Disconnect button: Error Connection interrupted
- [x] Not so nice "back" symbol in the upper right corner of the VPN selection list
- [ ] Show status site after connection has been established does not work
- [ ] Click on the dot icon in the upper right corner does nothing (what should happen there?)

> _Click on the dot icon in the upper right corner does nothing (what should happen there?)_
> it should minimize the window of the application directly to the tray, removing the application from the task bar.
> 
> Should I remove the dot from the menu?

No, please implement: click on the dot minimizes the window of the application directly to the tray, removing the application from the task bar.

**Comment by Tcheutchoua-Steve** [comment]
I will change it to i18n.tr("Login error: wrong username/password")
This string will need to be modified int he translations. Right now, what we have is just i18n.tr("Login error: ") in translations

**Comment by Tcheutchoua-Steve** [comment]
Could you pls include a snapshot of "Error Connection interrupted" when pressing Disconnect button? I can't seem to reproduce that on mine.

**Comment by flogat** [comment]
Hope this helps:

![image](https://user-images.githubusercontent.com/12492529/89331111-8220a180-d691-11ea-8a6b-0102fbc4863f.png)

```
0:30:43.887 [ReaderThread] INFO de.shellfire.vpn.client.Client - handleConnectionStateChanged()
20:30:43.888 [ReaderThread] INFO de.shellfire.vpn.client.Client - event: Reason: DisconnectDetected, ConnectionState: Connecting
20:30:43.888 [ReaderThread] DEBUG de.shellfire.vpn.gui.controller.ShellfireVPNMainFormFxmlController - connectionStateChanged Connecting, reason=DisconnectDetected
20:30:43.888 [ReaderThread] DEBUG de.shellfire.vpn.gui.controller.ShellfireVPNMainFormFxmlController - SetStateConnecting: Connnection in proessess
20:30:44.046 [ReaderThread] INFO de.shellfire.vpn.client.Client - handleConnectionStateChanged()
20:30:44.046 [ReaderThread] INFO de.shellfire.vpn.client.Client - event: Reason: DisconnectButtonPressed, ConnectionState: Disconnected
20:30:44.046 [ReaderThread] DEBUG de.shellfire.vpn.gui.controller.ShellfireVPNMainFormFxmlController - connectionStateChanged Disconnected, reason=DisconnectButtonPressed
août 04, 2020 8:30:45 PM org.apache.http.impl.execchain.RetryExec execute
INFOS: I/O exception (java.net.SocketException) caught when processing request to {s}->https://www.shellfire.de:443: Network is unreachable: connect
août 04, 2020 8:30:45 PM org.apache.http.impl.execchain.RetryExec execute
INFOS: Retrying request to {s}->https://www.shellfire.de:443
20:30:45.175 [JavaFX Application Thread] DEBUG de.shellfire.vpn.webservice.JsonHttpRequest - response received
20:30:45.176 [JavaFX Application Thread] DEBUG de.shellfire.vpn.webservice.JsonHttpRequest - HTTP/1.1 200 OK
```

**Comment by Tcheutchoua-Steve** [comment]
Yes, thanks it helps. 

It is a supposed response as  indicated in https://github.com/shell-fire/shellfire-vpn/blob/master/ShellfireVPN/src/main/java/de/shellfire/vpn/gui/controller/ShellfireVPNMainFormFxmlController.java#L729

Do we want a different behaviour?

**Comment by Tcheutchoua-Steve** [comment]
_Click on the dot icon in the upper right corner does nothing (what should happen there?)_
it should minimize the window of the application directly to the tray, removing the application from the task bar. 

Should I remove the dot from the menu?

**Comment by Tcheutchoua-Steve** [comment]
_Show status site after connection has been established does not work_
could you provide more info on this? Do you mean like opening the shellfire.de website?

**Comment by flogat** [comment]
> Yes, thanks it helps.
> 
> It is a supposed response as indicated in https://github.com/shell-fire/shellfire-vpn/blob/master/ShellfireVPN/src/main/java/de/shellfire/vpn/gui/controller/ShellfireVPNMainFormFxmlController.java#L729
> 
> Do we want a different behaviour?

Yes, expected behavior is that provided reasonForStateChange == Reason.DisconnectButtonPressed - hence no message should be shown. I believe there was some functionality to differentiate between "User Triggered disconnect" (=expected disconnect) and non-user-triggered-disconnect (e.g. process crash, something else) - this differentiation seems not to be working right...

**Comment by flogat** [comment]
> _Show status site after connection has been established does not work_
> could you provide more info on this? Do you mean like opening the shellfire.de website?

yes

**Comment by Tcheutchoua-Steve** [comment]
In the swing version, the status page appeared only for connexions that are not premium. Should I made the site open just for VPNs that are not premium or for all VPN types?

**Comment by flogat** [comment]
Hi, this is not about the PremiumNagScreen - this is about the settings menu, where it shows "open status page after connection ahs been established", which opens the user's web browser. 
The exact URL is retrieved from the API, for germany it is for example www.shellfire.de/status - this page verifies a successful connection to the VPN.

**Comment by Tcheutchoua-Steve** [comment]
Okay, I will look into that. Thank you

**Comment by flogat** [comment]
Closing this because i created separate issues for the individual topics
