### ISSUE TITLE
some bugs for florian

### ISSUE THREAD

**Issue by flogat** [shell-fire/shellfire-vpn#14]
•	[ ] Austart/Autoconnect funktioniert nicht
•	[ ] Save login data funktioniert nicht (beim nächsten Start: Null response received)

**Comment by flogat** [comment]
I think this might be related to #19 as they all somehow relate to preferences not being stored correctly.

I believe my previous implementation was using the VpnProperties (custom made) instead of the generic Preferences class. Is it possible that you changed something here during the conversion to fxml? Please check the history @Tcheutchoua-Steve 

Thanks

**Comment by Tcheutchoua-Steve** [comment]
Okay noted @flogat

**Comment by flogat** [comment]
Found it - fixed it! if interested, take a look at the commit - the username field was used to write the data to the Preferences, not the value from the form...

**Comment by flogat** [comment]
closed by 0b0acc7bf1ca7b78d5eb414a2f3ef550a0c387bf
