### ISSUE TITLE
When pressing Disconnect button: Error Connection interrupted

### ISSUE THREAD

**Issue by flogat** [shell-fire/shellfire-vpn#17]
Separate issue for better handling of individual bugs

Could you pls include a snapshot of "Error Connection interrupted" when pressing Disconnect button? I can't seem to reproduce that on mine.
![image](https://user-images.githubusercontent.com/12492529/91872940-c2674580-ec78-11ea-8f1b-9f20349bd36f.png)

```
0:30:43.887 [ReaderThread] INFO de.shellfire.vpn.client.Client - handleConnectionStateChanged()
20:30:43.888 [ReaderThread] INFO de.shellfire.vpn.client.Client - event: Reason: DisconnectDetected, ConnectionState: Connecting
20:30:43.888 [ReaderThread] DEBUG de.shellfire.vpn.gui.controller.ShellfireVPNMainFormFxmlController - connectionStateChanged Connecting, reason=DisconnectDetected
20:30:43.888 [ReaderThread] DEBUG de.shellfire.vpn.gui.controller.ShellfireVPNMainFormFxmlController - SetStateConnecting: Connnection in proessess
20:30:44.046 [ReaderThread] INFO de.shellfire.vpn.client.Client - handleConnectionStateChanged()
20:30:44.046 [ReaderThread] INFO de.shellfire.vpn.client.Client - event: Reason: DisconnectButtonPressed, ConnectionState: Disconnected
20:30:44.046 [ReaderThread] DEBUG de.shellfire.vpn.gui.controller.ShellfireVPNMainFormFxmlController - connectionStateChanged Disconnected, reason=DisconnectButtonPressed
août 04, 2020 8:30:45 PM org.apache.http.impl.execchain.RetryExec execute
INFOS: I/O exception (java.net.SocketException) caught when processing request to {s}->https://www.shellfire.de:443: Network is unreachable: connect
août 04, 2020 8:30:45 PM org.apache.http.impl.execchain.RetryExec execute
INFOS: Retrying request to {s}->https://www.shellfire.de:443
20:30:45.175 [JavaFX Application Thread] DEBUG de.shellfire.vpn.webservice.JsonHttpRequest - response received
20:30:45.176 [JavaFX Application Thread] DEBUG de.shellfire.vpn.webservice.JsonHttpRequest - HTTP/1.1 200 OK
```

Yes, thanks it helps.

It is a supposed response as indicated in https://github.com/shell-fire/shellfire-vpn/blob/master/ShellfireVPN/src/main/java/de/shellfire/vpn/gui/controller/ShellfireVPNMainFormFxmlController.java#L729

Do we want a different behaviour?

Yes, expected behavior is that provided reasonForStateChange == Reason.DisconnectButtonPressed - hence no message should be shown. I believe there was some functionality to differentiate between "User Triggered disconnect" (=expected disconnect) and non-user-triggered-disconnect (e.g. process crash, something else) - this differentiation seems not to be working right...

**Comment by Tcheutchoua-Steve** [comment]
There are two [ReaderThread] INFO de.shellfire.vpn.client.Client - events. 

1. 20:30:43.888 [ReaderThread] INFO de.shellfire.vpn.client.Client - event: Reason: DisconnectDetected, ConnectionState: Connecting
2. 20:30:44.046 [ReaderThread] INFO de.shellfire.vpn.client.Client - event: Reason: DisconnectButtonPressed, ConnectionState: Disconnected

(1) has reason DisconnectedDetected and 
(2) has reason DisconnectButtonPressed. 

So 1. should be the thread causing "Error Connection Interrupted.". I will dig to see how they can be addressed properly.

**Comment by flogat** [comment]
this commit I just mentioned might actually resolve this issue with the paralel threads...
re-test needed.

**Comment by Tcheutchoua-Steve** [comment]
There are no more two threads started when the connect button is pressed. I'm pretty sure the commit you made solves this issue.

**Comment by Tcheutchoua-Steve** [comment]
I couldn't reproduce this bug when it was existing. Maybe cross-check and close the ticket @flogat ?

**Comment by flogat** [comment]
Yes, does not occur for me anymore, too - closing #17 herewith
