### ISSUE TITLE
Show status site after connection has been established does not work

### ISSUE THREAD

**Issue by flogat** [shell-fire/shellfire-vpn#19]
When this setting is enabled:
![image](https://user-images.githubusercontent.com/12492529/91873514-651fc400-ec79-11ea-839c-ccd6dfefceb0.png)

After the connection has been established, the user's web browser should be opened and directed to the URL that is provided by the api from the call getUrlSuccesfulConnect

**Comment by flogat** [comment]
Seems this is never actually called:

https://github.com/shell-fire/shellfire-vpn/blob/19a8dec247186744620346e1deefaf8e034d62e5/ShellfireVPN/src/main/java/de/shellfire/vpn/gui/controller/ShellfireVPNMainFormFxmlController.java#L1091

**Comment by Tcheutchoua-Steve** [comment]
In progress

**Comment by Tcheutchoua-Steve** [comment]
The method is found in connected `setStateConnected`() method though https://github.com/shell-fire/shellfire-vpn/blob/19a8dec247186744620346e1deefaf8e034d62e5/ShellfireVPN/src/main/java/de/shellfire/vpn/gui/controller/ShellfireVPNMainFormFxmlController.java#L1087 
digging more

**Comment by flogat** [comment]
Yes so this is why I believe it might be related to the Preferences:

```
	private boolean showStatusUrl() {
            Preferences prefs = this.getPreferences();

            boolean showStatus = prefs.getBoolean(LoginController.REG_SHOWSTATUSURL, false);
            return showStatus;
	}
```

**Comment by Tcheutchoua-Steve** [comment]
Exactly. I discovered that yesterday.

**Comment by flogat** [comment]
Hi @Tcheutchoua-Steve,
any update on this Preferences usage? Did you check the usage prior to the fxml migration activities?
Thanks
- Florian

**Comment by Tcheutchoua-Steve** [comment]
Not yet checked that @flogat , my bad. I instead thought you had to do something on the preferences first. I will check that.
