### ISSUE TITLE
Ensure all tray actions are impemented

### ISSUE THREAD

**Issue by Tcheutchoua-Steve** [shell-fire/shellfire-vpn#21]
Some tray icon actions like exit are not implemented. Cross check and implement them all.

**Comment by Tcheutchoua-Steve** [comment]
Exit implemented in https://github.com/shell-fire/shellfire-vpn/commit/f758f8a639392c2b568b7b8615b18b03be4512d0

**Comment by flogat** [comment]
Todo - on-the-fly editing of trayicon popup-menu entry for "connect"

The current design is like this:
When disconnected:
- show "connect" (done)
- when click on "connect", perform a connect (done)

When connecting:
- show "connecting" (done)
- cannot click anything (e.g. no abort possible) (todo)

When connected:
- show "disconnect" (todo)

I like it overall, but I see 2 issues with this approach:

1) During "connecting" phase, user cannot abort from popup menu
To resolve this, I suggest to add an "abort" menuitem during connecting phase

2) It is not nicely optically separated, so hard to see that something is happening there
To resolve this, I suggest to move the "connect" menuItem (and to-be-created "abort" item during connecting phase) to the top and separate it with a Separator Line https://docs.oracle.com/javase/tutorial/uiswing/components/separator.html

3) possibly, optics could be improved by using icons next to the actionable menu items

We may split these individual items into separate issues if needed.

@Tcheutchoua-Steve , please take a look, I might continue working on it tomorrow morning of evening in case of no progress - thanks

**Comment by Tcheutchoua-Steve** [comment]
Could you have a look and test https://github.com/shell-fire/shellfire-vpn/commit/4d16564064f73e365fe7df82bf861db73dcd736d , @flogat ?

**Comment by flogat** [comment]
Well done Steve - just what I expected!
However, there is slight problem - reproduce:
1) Press connect (either in popup or main screen)
2) Keep the popupmenu open
3) Wait

During some time while the connection is being established, the PopupMenu is resized and only very small - then it stays this way:
![image](https://user-images.githubusercontent.com/12492529/95545264-ba2fc200-09fd-11eb-8220-0330875f4ba6.png)

I did not have time to analyze the timing exactly, but think it happens during the call when the TrayIcon Image is changed.

What I looked into without success:
- trying to find a .revalidate() or .repaint() method - seems to be unavailable for the java.awt.PopupMenu we're using
- wrapping the modifications (additions and removals) of the popupmenuitems into "Platform.runLater", but without success

An alternative solution might be to not modify the list of menu items (e.g. remove/add) but to have all the menuitems available at all items, and only "enable" / "disable" them with ".setVisible(true)" and ".setVisible(false). 

Please investigate.

**Comment by flogat** [comment]
Another alternative could be to only change the text on the menuitems and to have the actionListeners on them either replaced or be status-aware...

**Comment by Tcheutchoua-Steve** [comment]
Thanks for the input & suggestions. I will look into them 👍🏼

**Comment by Tcheutchoua-Steve** [comment]
After checking the code for MenuItem.insert() I noticed that the internal implementation removes and adds back all of the existing items. I think that is what caused the changes in size. 
The workaround I propose is to not use insert but instead add methods. This, however, will cause the changing bottom (abort, connect, disconnect) to be placed at the bottom of the tray. 
You could have a look at https://github.com/shell-fire/shellfire-vpn/commit/e6bf3e5f36fa7d7c6c99e70997b540c9f629ac33 

If that is not ok, we can still consider using one menu item at the top with changing labels (and of course changing listeners)

**Comment by flogat** [comment]
I think it is good the way it is - and it works fine, so nothing else to fix here.
Only thing I changed slightly was the actual label text, to have the words begin with upper case letters.
