### ISSUE TITLE
ServerList Screen: For free VPN, 2 connect buttons shown

### ISSUE THREAD

**Issue by flogat** [shell-fire/shellfire-vpn#25]
When a free vpn is selected, on the main screen everything is as expected:
- on the lower left hand side, there is the connect button
- on the lower right hand side, there is the "Shellfire VPN Premium Infos" button

However on the serverlist screen:
- on the lower left hand side, there is the connect button
- on the lower right hand side, there is another connect button with the german label for "connect", which is "verbinden"

Acceptance Criteria:
- Lower right hand button in server list screen hidden for Premium/PremiumPlus vpns
- Lower right hand button in server list screen visible with same label and behaviour as on main screen: Show "Shellfire VPN Premium Infos"

**Comment by flogat** [comment]
Correct:
![image](https://user-images.githubusercontent.com/12492529/94888641-1339ac00-047a-11eb-96b7-cf95a30c4942.png)

Wrong:
![image](https://user-images.githubusercontent.com/12492529/94888667-28163f80-047a-11eb-9a2f-1517babff5c3.png)

**Comment by flogat** [comment]
@Tcheutchoua-Steve , please fix this

**Comment by Tcheutchoua-Steve** [comment]
okay, I'm on this @flogat.
