### ISSUE TITLE
Connect button positioning inconsistent

### ISSUE THREAD

**Issue by flogat** [shell-fire/shellfire-vpn#26]
In Main Screen and Server List Screen, the positioning of the Connect button(s) is not aligned - this leads to the effect that the buttons "jump" when switching back and forth between the menu entries.

Please align the button position over the 2 screens:
![grafik](https://user-images.githubusercontent.com/12492529/95024780-a0048580-0685-11eb-9642-110dd5fb926c.png)
![grafik](https://user-images.githubusercontent.com/12492529/95024794-b4488280-0685-11eb-83ee-ed7aa8a6415d.png)

@Tcheutchoua-Steve , please fix, should be easy for you - thanks!

**Comment by Tcheutchoua-Steve** [comment]
Should be fixed in https://github.com/shell-fire/shellfire-vpn/commit/5f4c23caa433bca20f37fd888bc098ea04f2be1b and https://github.com/shell-fire/shellfire-vpn/commit/9cb57209111b51de1f30192a0317069f239a346a
Please have a look @flogat

**Comment by flogat** [comment]
thanks @Tcheutchoua-Steve  - 5f4c23c is indeed the fix version - closing #26
