### ISSUE TITLE
Convert DownloadProgressDialog to javaFx

### ISSUE THREAD

**Issue by Tcheutchoua-Steve** [shell-fire/shellfire-vpn#27]
DownloadProgressDialog  still extends a swing class, it should be converted to JavaFx 
https://github.com/shell-fire/shellfire-vpn/blob/master/ShellfireVPN/src/main/java/de/shellfire/vpn/updater/DownloadProgressDialog.java#L26

**Comment by flogat** [comment]
it works fine as it is and will also be okay-readable on 4k resolution, so let's not do this one for now

**Comment by Tcheutchoua-Steve** [comment]
okay
