### ISSUE TITLE
Shellfire VPN for Windows: Connecting / Disconnecting sluggish and with high CPU usage

### ISSUE THREAD

**Issue by flogat** [shell-fire/shellfire-vpn#29]
When I click the Connect or Disconnect button, the CPU cooler spins up and it takes very long, until something happens, even on strong hardware.

**Comment by flogat** [comment]
I cannot reproduce it. @Tcheutchoua-Steve can you reproduce this behaviour?

**Comment by flogat** [comment]
@mbehrsf please retest with newest build

**Comment by mbehrsf** [comment]
I think the CPU usage might have gotten a bit better, but connecting and disconnecting still seems sluggish (might be related to https://github.com/shell-fire/shellfire-vpn/issues/36 )

**Comment by flogat** [comment]
@mbehrsf - can you check in the task manager, which process exactly has high cpu usage with exactly which activity please?
other wise we cannot reproduce this

**Comment by mbehrsf** [comment]
I took a closer look, it seems there is indeed no high CPU usage. What mainly bothers me is that clicking "Disconnect", the app freezes for a few seconds, sometimes producing a "java is not responding" error before the disconnect actually happens. Could be the same problem or related to https://github.com/shell-fire/shellfire-vpn/issues/39

**Comment by flogat** [comment]
@mbehrsf can we close this issue then?

**Comment by mbehrsf** [comment]
yes, closing
