### ISSUE TITLE
Shellfire VPN for Windows Showconsole window too large

### ISSUE THREAD

**Issue by flogat** [shell-fire/shellfire-vpn#31]
I cannot see/click send log because the button is outside of the screen. Again, I am using 1920x1080p and 150% scaling.

**Comment by Tcheutchoua-Steve** [comment]
Okay, I will cross-check with the former size and adjust.

**Comment by Tcheutchoua-Steve** [comment]
Should be solved with commit https://github.com/shell-fire/shellfire-vpn/commit/e2ef72fb65cf3f5521f320c3aeb3f4341a69c1fb. 
Please check @flogat

**Comment by flogat** [comment]
@mbehrsf  please retest

**Comment by mbehrsf** [comment]
looks good!
