### ISSUE TITLE
Shellfire VPN for Windows impossible to cancel sending a log

### ISSUE THREAD

**Issue by flogat** [shell-fire/shellfire-vpn#32]
Whenever I want to cancel sending a log, I click "Cancel" then "OK" and ist starts sending again.

**Comment by flogat** [comment]
after new build has been provided...

**Comment by mbehrsf** [comment]
With the new build, when I click "Send log" a "Connecting" indicator appears as if I was trying to connect to the VPN, then a "Log has been sent" message appears, although the log was not sent because there was no internet connection. There should be an error saying "Log could not be sent" instead.

**Comment by flogat** [comment]
Done: proper handling and error message when no internet connection available
Todo: handling of timeouts, possibility to cancel sending

**Comment by flogat** [comment]
fixed this, ready for retest.
this fix has some possible side effect as it changes some general ways in which the webservice is accessed, so adding a separate issue to retest this.

**Comment by flogat** [comment]
new test issue is #41

**Comment by flogat** [comment]
closing this issue, because further detailled tests will be handled as new issues, or within the comments of #41
