### ISSUE TITLE
Clicking the Shellfire VPN icon multiple times opens multiple instances of the app

### ISSUE THREAD

**Issue by flogat** [shell-fire/shellfire-vpn#34]
There should never be more than 1 instance of Shellfire VPN running at the same time.

**Comment by flogat** [comment]
please retest once new build delivered

**Comment by mbehrsf** [comment]
With the new build, the splash screen appears, then the "testing for endpoints" screen, then an error that says "already running" appears. I guess we can close the issue if this is elegant enough?

**Comment by flogat** [comment]
Yes I think this is elegant enough, should not really happen in real life too often...? @mbehrsf  please close if you agree. :)
