### ISSUE TITLE
No desktop Icon displayed (Windows 7)

### ISSUE THREAD

**Issue by flogat** [shell-fire/shellfire-vpn#38]
- A desktop link to start Shellfire VPN is being created, but it has not Shellfire icon.
- Note: Icon correctly appears after reboot
- Windows 10 works fine, maybe it was just a problem of my PC after I first uninstalled 2.8

**Comment by flogat** [comment]
this should be a bug already for many versions.
should be fixed within nsis installer using this additional Refresh code: https://nsis.sourceforge.io/RefreshShellIcons

**Comment by mbehrsf** [comment]
looks fixed, closing
