### ISSUE TITLE
Quick disconnect leads to problems

### ISSUE THREAD

**Issue by mbehrsf** [shell-fire/shellfire-vpn#39]
If I hit the "Disconnect" button immediately after the connection has been established, I seem to get stuck in an eternal "Connecting" state. I can cancel this by clicking "Cancel". This does not happen if I wait a few seconds before I click "Disconnect" after the connection has been established, only happens when I do it quickly.

**Comment by flogat** [comment]
could be fixed with the fixes for #29, please retest

**Comment by flogat** [comment]
From @mbehrsf 's email: "ah uh sry das hatte ich wohl überlesen. Ja, ist schon sehr viel snappiger geworden. Klicke da gerade ein  bisschen wild rum umd glaub es geht soweit alles."

Can we close this issue then?

**Comment by mbehrsf** [comment]
looks good on both win 7 and 10. closing.
