### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by flogat** [shell-fire/shellfire-vpn#44]
Check and update translations, some strings were updated during recent refactorings.

**Comment by flogat** [comment]
@mbehrsf , I provided you some translations via email, please provide the tranlations back

**Comment by mbehrsf** [comment]
Plese re-send, I don't see any mail.

**Comment by flogat** [comment]
resend done, probably related to my outlook configuration not being up to date...

**Comment by mbehrsf** [comment]
translated and sent
